{
 "title": "Performance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (EclipseStore)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name) (increase(container_cpu_usage_seconds_total{name=~\"^.*eclipsestore-server-1.*$\"}[1m])) / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Usage (EclipseStore)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (jvm_memory_used_bytes{instance=\"eclipsestore-server:8080\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_used_bytes{instance=\"postgres-server:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (Postgres)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name) (increase(container_cpu_usage_seconds_total{name=~\"^.*postgres-server-1.*$\"}[1m])) / 60",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum by(name) (increase(container_cpu_usage_seconds_total{name=~\"^.*db-1.*$\"}[1m])) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage (Postgres)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Postgres" },
    {
     "expr": "sum by(instance) (jvm_memory_used_bytes{instance=\"postgres-server:8080\"})",
     "legendFormat": "Java"
    }
   ]
  },
  {
   "title": "Requests/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage (All Containers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name) (increase(container_cpu_usage_seconds_total{name!=\"\"}[1m])) / 60",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}