global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "servers"
    metrics_path: "/prometheus"
    static_configs:
      - targets:
        - "postgres-server:8080"
        - "eclipsestore-server:8080"
  - job_name: "postgres"
    metrics_path: "/metrics"
    static_configs:
      - targets:
        - "postgres-metrics-exporter:9187"
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]