{
 "title": "Performance Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (EclipseStore) [100% = 1 core]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name) (increase(container_cpu_usage_seconds_total{name=~\"^.*eclipsestore-server-1.*$\"}[1m]) / 60)",
     "legendFormat": "EclipseStore Micronaut DataProvider"
    }
   ]
  },
  {
   "title": "RAM Usage (EclipseStore)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (jvm_memory_used_bytes{instance=\"eclipsestore-server:8080\"})",
     "legendFormat": "EclipseStore Micronaut DataProvider"
    }
   ]
  },
  {
   "title": "CPU Usage (Postgres) [100% = 1 core]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name) (increase(container_cpu_usage_seconds_total{name=~\"^.*postgres-server-1.*$\"}[1m]) / 60)",
     "legendFormat": "Postgres Micronaut DataProvider"
    },
    {
     "expr": "sum by(name) (increase(container_cpu_usage_seconds_total{name=~\"^.*db-1.*$\"}[1m]) / 60)",
     "legendFormat": "PostgreSQL Database"
    }
   ]
  },
  {
   "title": "RAM Usage (Postgres)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"postgres-metrics-exporter:9187\"}",
     "legendFormat": "PostgreSQL Database"
    },
    {
     "expr": "sum by(instance) (jvm_memory_used_bytes{instance=\"postgres-server:8080\"})",
     "legendFormat": "Postgres-Micronaut DataProvider"
    }
   ]
  },
  {
   "title": "Requests/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_sum[1m]) / increase(http_server_requests_seconds_count[1m])",
     "legendFormat": "{{method}} {{instance}}{{uri}}"
    }
   ]
  }
 ]
}